name: Publish via GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Get Python version from pyproject.toml
        id: python-version
        run: |
          # Extract the Python version requirement from pyproject.toml
          version=$(grep 'requires-python' pyproject.toml | sed -E 's/.*(>=.*)/\1/' | tr -d '"')
          echo "python_version=$version" >> $GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          # python-version: ">=3.12"
          python-version: ${{ env.python-version }}

      - name: Setup Poetry
        uses: pronovic/setup-poetry@v2
        with:
          version: "2.1.1"
          cache-venv: "true"
          cache-poetry: "true"

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # - run: pip install -r requirements.txt
      - run: poetry install

      # - run: mkdocs gh-deploy -f src/mkdocs.yml --force
      - run: poetry run mkdocs gh-deploy -f src/mkdocs.yml --force
